# Builds the dist folder for any pull requests

name: build-dist

on:
  pull_request:
    branches:
      - main

jobs:
  build-dist:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: install
        run: npm ci
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: build dist'
